# Generated by Django 2.0.1 on 2018-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('S', 'Saturday'), ('W', 'Wednesday'), ('M', 'Monday'), ('F', 'Friday'), ('Th', 'Thursday'), ('Tu', 'Tuesday')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('bits_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
            ],
        ),
    ]
