# Generated by Django 2.0.1 on 2018-02-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDC',
            fields=[
                ('COMP_CODES', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=30)),
                ('units', models.CharField(max_length=2, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('sem', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5, null=True)),
                ('class_nbr', models.CharField(max_length=4, null=True, unique=True)),
                ('section', models.CharField(max_length=2, null=True)),
                ('room', models.CharField(max_length=10, null=True)),
                ('class_pattern', models.CharField(max_length=4, null=True)),
                ('mtg_start', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('instructor_ID', models.CharField(max_length=20, null=True)),
                ('instructor_name', models.CharField(max_length=30, null=True)),
                ('instructor_role', models.CharField(max_length=2, null=True)),
                ('exam_tm_cd', models.CharField(max_length=5, null=True)),
                ('exam_date', models.DateField(null=True)),
                ('course_admin', models.CharField(max_length=5, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.CDC')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False)),
                ('CAMPUS_ID', models.CharField(max_length=13, null=True)),
                ('NAME', models.CharField(max_length=100, null=True)),
                ('YEAR', models.CharField(max_length=4, null=True)),
                ('DISC', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
