# Generated by Django 2.0.1 on 2018-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDC',
            fields=[
                ('comp_codes', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=30)),
                ('units', models.CharField(max_length=2, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('sem', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('course_id', models.CharField(blank=True, max_length=6)),
                ('class_nbr', models.CharField(blank=True, max_length=4, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLID', models.CharField(blank=True, max_length=11)),
                ('CAMPUS_ID', models.CharField(max_length=13, null=True)),
                ('CRSE_ID', models.IntegerField(null=True)),
                ('SUBJECT', models.CharField(max_length=6, null=True)),
                ('CATALOG_NBR', models.CharField(max_length=4, null=True)),
                ('DESCR', models.CharField(max_length=20, null=True)),
                ('CLASS_NBR', models.IntegerField(null=True)),
                ('CLASS_SECTION', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False)),
                ('CAMPUS_ID', models.CharField(max_length=13, null=True)),
                ('NAME', models.CharField(max_length=100, null=True)),
                ('YEAR', models.CharField(max_length=4, null=True)),
                ('DISC', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
