# Generated by Django 2.0.1 on 2018-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdc',
            name='sem',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cdc',
            name='units',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cdc',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='courseslot',
            name='class_nbr',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
