# Generated by Django 2.0.1 on 2018-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslot',
            name='days',
            field=models.CharField(choices=[('Tu', 'Tuesday'), ('S', 'Saturday'), ('M', 'Monday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], max_length=2),
        ),
    ]
