# Generated by Django 2.0.1 on 2018-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('courseSlots', models.ForeignKey(on_delete='PROTECT', to='main.CourseSlot')),
            ],
        ),
    ]
