# Generated by Django 2.0.1 on 2018-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180130_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslot',
            name='days',
            field=models.CharField(choices=[('W', 'Wednesday'), ('F', 'Friday'), ('S', 'Saturday'), ('M', 'Monday'), ('Tu', 'Tuesday'), ('Th', 'Thursday')], max_length=2),
        ),
    ]
