# Generated by Django 2.0.1 on 2018-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180212_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdc',
            name='comp_codes',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
