# Generated by Django 2.0.1 on 2018-02-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='courseSlots',
        ),
        migrations.AddField(
            model_name='map',
            name='courseSlots',
            field=models.ManyToManyField(to='main.CourseSlot'),
        ),
    ]
