# Generated by Django 2.0.1 on 2018-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180212_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdc',
            name='comp_codes',
            field=models.CharField(blank=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
